### ISSUE TITLE
Cast from mobile site

### ISSUE THREAD

**Issue by CodeDruid13** [castjs/castjs#16]
Am building a site aimed at mobile users and the cast feature doesn't seem to work on mobile

**Comment by Fenny** [comment]
The browser must support the cast function, what browser are you using?

**Comment by dutscher** [comment]
I cast from Desktop everything works fine:
Google Chrome Version 86.0.4240.111 (Offizieller Build) (64-Bit)

But on Mobile:
Google Chrome Version 86.0.4240.99 

The Duration didn't work and the inital session event needs long time when a cast ist runnning.
This is what CodeDruid13 means. The cast is working for me but not as aspected as on desktop.

Cheers

**Comment by dutscher** [comment]
after a small debug into your code:
cast.framework.CastContext.getInstance().getCurrentSession().getCastDevice().friendlyName; returns the name of my chromecast and says session resumed. but the media data is empty
![image](https://user-images.githubusercontent.com/14682/96838172-ca0cc480-1447-11eb-9d3f-5f87d4bc2a1a.png)

cheers
