### ISSUE TITLE
Get available cast devices

### ISSUE THREAD

**Issue by tehuster** [castjs/castjs#17]
Is it possible to get a list with the available cast devices with this library?

**Comment by Fenny** [comment]
Hey @tehuster, it is currently limited to cast to only 1 case device on the network ( the one you choose ). But this is an interesting idea, I might add this in the future 👍

**Comment by tehuster** [comment]
Hey @Fenny, thanks for the reply. I think my question was a little confusing because my goal is not to cast to multiple devices. 
I was wondering if it's possible to get a list with all available devices without using the "google cast tab". So i can make an UI myself for all available devices and let the user select a device without using that previous named tab.

**Comment by Fenny** [comment]
Ah I see, that is not possible. I remember trying that back in 2018, maybe they updated their API ( not sure ). But the user must select the cast device from the chromium engine.

**Comment by WarKaa** [comment]
Hi @Fenny, any news on this ?
Is it still a limitation from the Chromcast Web SDK ? 
And is it possible to cast two videos silmutaneously on two chromecast devices ?
Thank you for you work
