### ISSUE TITLE
Mobile Chrome Session Resume Problem

### ISSUE THREAD

**Issue by dutscher** [castjs/castjs#20]
hey there,
i used your demo code and i got a session resume problem under the mobile chrome 
![Screenshot_20201023-081351~2](https://user-images.githubusercontent.com/14682/96963096-541c6200-1508-11eb-8568-f95604fd6d7d.png)
when i cast a mp4, everythin works fine. but after a reload the session didnt startet via your framework. when i debug into the api of chromecast i got a session resume. but no media info. what works is to change the volume. but the other events didnt triggered. 
can you confirm this with your demo code?

cheers

**Comment by Fenny** [comment]
Hi @dutscher, I can confirm I have the same issue with Chrome 86.0.4240.99 on Android 10.
I will try to debug tonight and see why this is happening on mobile and not desktop.

**Comment by dutscher** [comment]
jip i thought that would be a chromecast bug. 
but maybe your framework is able to detect the resumed session and trigger some events.
the weird thing is sometimes i got the media infos after reload. but cant find out why this is happen.
thanks for your effort!

cheera

**Comment by Fenny** [comment]
I was debugging all night without a single successful reload, could you tell me a bit more on how you sometimes get the media info?

**Comment by dutscher** [comment]
i found the "hack".
you need the google home app installed and connected to your chromecast.
when the notification is coming that a cast is run u can pause it. press play and in the background the castjs will resume playing :D but without duration...
![Screenshot_20201024-144452](https://user-images.githubusercontent.com/14682/97082149-d475bc80-1607-11eb-9311-6797496541b2.png)
its only possible due a sdk fix... so bad for us.
but maybe your code can detect the resume?

cheers

**Comment by dutscher** [comment]
mysterious is that this is working: 
```
if (cc.session) {
            const next = cc.volumeLevel + 0.1;
            if (next <= 1) {
                cc.volume(next);
            }
        }
```
but cc.play() and cc.pause() not...

**Comment by Fenny** [comment]
Yeah we can detect the resume, but even if I manually request the media data from the cast device it returns null :(

**Comment by dutscher** [comment]
mediainfo after casting:
![mobile media-session](https://user-images.githubusercontent.com/14682/97088963-b1153680-1634-11eb-9c04-65e6b85b796e.png)
mediainfo after reload "null" after only paused via google home the media session is available but nothing inthere:
![image](https://user-images.githubusercontent.com/14682/97088957-a3f84780-1634-11eb-92cb-8855f3a9922d.png)

puhh i hope they fix this asap :D
which chromecast do you have?

cheers

**Comment by Fenny** [comment]
I got the exact same findings yesterday, I tried many things to fix this.

- Use cast API directly without the cast framework
- Use different join policies
- Play with different options

But unfortunately, it resulted in the same behavior as above ( only Android Chrome ).

Maybe there is a possibility to create a custom receiver to use the message bus for communicating via messages.
So we bypass the cast framework and do all the logic on the receiver, have to think about it.

Will continue to play around, until then I might add a disclaimer message to the GitHub readme that Chrome on Android devices do not support re-joining sessions

**Comment by dutscher** [comment]
jip i use the usb-c cable and the developer console of my desktop chrome via "remote devices".

cheers

**Comment by Fenny** [comment]
I have the exact same result with a custom receiver, after some further debugging I noticed one difference between mobile and desktop that might have something to do with it.

**Chrome Mobile** displays **web-4** as `transportId` after refresh
![](https://i.imgur.com/5fF7Kht.png)

**Chrome Desktop** displays the actual session as `transportId` after refresh
![](https://i.imgur.com/LE6FLDo.png)

**Comment by dutscher** [comment]
there is acitivity in the issue tracker :)

**Comment by Fenny** [comment]
Yeah, but no fix yet :(

**Comment by Fenny** [comment]
@dutscher they still didn't fix the issue, but I found a work-around by passing 'origin_scoped' as joinpolicy.

```js
new Castjs({
   joinpolicy: 'origin_scoped'
})
```
