### ISSUE TITLE
Not working on Brave by default

### ISSUE THREAD

**Issue by Albermonte** [castjs/castjs#22]
Since Brave is on the supported browser I decided to try on my Desktop PC encountering this error:

`[18:05:58] error		: Casting is not supported in this browser`

Brave Versión 1.17.73 Chromium: 87.0.4280.67 (Build oficial) (64 bits)

The fix to this issue is enabling `Media Router` on Brave Settings and restarting the browser, maybe you would want to include it on the Readme

**Comment by Fenny** [comment]
I always thought Media Router is enabled by default, my bad. PR's are welcome!

**Comment by Fenny** [comment]
@Albermonte added brave!
![image](https://user-images.githubusercontent.com/25108519/185749421-b12374ed-eb70-4db0-993d-82a898ef62e6.png)
