### ISSUE TITLE
Issue reconnecting

### ISSUE THREAD

**Issue by Pollo00S** [castjs/castjs#23]
Hello, i'm currently experiencing an issue.
Sometimes after disconnecting and reconnecting to de devicce, the video start, but no event get tirggered, and i'm not able to know anything about the state of the video..

So, in few words:
Connect to device
Disconnect to device (after the video started)

And going on..
Sometimes the video start but no event get triggered (so, no timeupdate, no statechange, ...)

Is anyone experiencing that?

**Comment by Pollo00S** [comment]
Code example below:

    function castVideo()
    {
        if (cjs.available) {
            cjs.cast('http://192.168.1.9/' + data['videoLocation'],{
                poster: 'http://192.168.1.9/' + data['Poster'],
                title: data['Title'] + " (" + data['Date'] + ")",
                description: '',
            });
        }
        else
        {
            alert('Browser not supported');
        }
    }

    cjs.on('connect', () => {
        $('#cast').attr('onclick','cjs.disconnect()').text('cast_connected');
        console.log(cjs.device);
    });
    cjs.on('disonnect', () => {
        $('#cast').attr('onclick','castVideo()').text('cast');
    });

**Comment by Fenny** [comment]
What browser are you using?

**Comment by Fenny** [comment]
@Pollo00S try to add `origin_scoped` joinpolicy
![image](https://user-images.githubusercontent.com/25108519/185748046-22c6ec4b-1c43-4c38-9840-21ef51e962c3.png)

```js
new Castjs({
    joinpolicy: 'origin_scoped'
});
```
