### ISSUE TITLE
List and choose device

### ISSUE THREAD

**Issue by arqtiq** [castjs/castjs#28]
Hello,

I found this project I could use, but I'd need to be able to list and choose a device from that list to cast to.
Is this something possible, and if so, do you plan to implement it ?

Thanks

**Comment by realmilandev** [comment]
on chrome it already pops up a list when you use the .cast() thing
it opens the media hub on top right for me

**Comment by Fenny** [comment]
@arqtiq browsers and android devices have their own pop-up list of available devices, they should be listed automatically.
Brave/Chrome for example: 
![image](https://user-images.githubusercontent.com/25108519/185748263-9460299d-a5e7-462d-b74a-6b96ceed7c0f.png)
