### ISSUE TITLE
Playing next video automatically when current cast video ended

### ISSUE THREAD

**Issue by stephnlynn** [castjs/castjs#30]
Is it possible to play next video by writing new cast in the castjs "end" event?
I use the code below but it doesn't work.

cjs.on('end',          ()  => { cjs.cast('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4');});

Is there any other way to implement it?

**Comment by Pollo00S** [comment]
Hi, have u found a solution?

**Comment by Fenny** [comment]
Could use some help

**Comment by Fenny** [comment]
@stephnlynn casting new media will use the current session in `v5.1.0`
```js
cjs.on('end', () => { 
    cjs.cast('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4');
})
```
