### ISSUE TITLE
Available event not triggered

### ISSUE THREAD

**Issue by tvinko** [castjs/castjs#38]
Sometimes the available event is not triggered. I'm using Chrome on Mac Pro. 
The code is nothing special:
```
var cjs = new Castjs();
cjs.on('error', function (e) { console.log('chromecast:' + e); });
cjs.on('available', function () { console.log('available'); });
```

Are there any known issues related to this?

**Comment by Fenny** [comment]
A bit late, but thanks @tvinko for the issue report. Should be fixed in v5.3.0

https://github.com/castjs/castjs/releases/tag/v5.3.0
