### ISSUE TITLE
HLS stream with AES-128 encryption not working

### ISSUE THREAD

**Issue by novusbd** [castjs/castjs#39]
When I try the stream without encryption, the casting works without any issues. But with encryption the casting stops right after going into "Buffering" state.  The Encryption key has been successfully retrieved from the license URL but for some reason it's not working.
The encrypted stream works fine with multiple web players. So the encryption key delivery is fine. Has anyone experienced this issue? Please let me know if you have any solution.

**Comment by Fenny** [comment]
It looks like you need to develop a custom receiver app to handle this encryption. The default one does not seem to support AES-128 decryption.

You can supply your own receiver id using 

```js
new Castjs({
    receiver: 'YOURID' // Default = CC1AD845
});
```
